<h1>Categorias</h1>
<br>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Ação</th>
    </tr>
    <?php foreach($this->data as $entity): ?>
    <tr>
        <td><?php echo $entity->getId()?></td>
        <td><?php echo $entity->getNome()?></td>
        <td></td>
    </tr>
    <?php endforeach; ?>
</table>

<br>

<?php echo $this->paginationControl($this->data,'Sliding','paginator'); ?>
