<h1>Nova Categoria</h1>
<br>

<?php 
$form = $this->form; 
$form->setAttribute('action',$this->url('livraria-admin',array('controller' => 'categorias', 'action' => 'new')));

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<?php
echo $this->formRow($form->get('nome')).'<br><br>';
?>


<?php
echo $this->formSubmit($form->get('submit'));
?>

<?php
echo $this->form()->closeTag();
?>
