<h1>Novo Usuário</h1>
<br>

<?php 
$form = $this->form; 
$form->setAttribute('action',$this->url('livraria-admin',array('controller' => 'users', 'action' => 'new')));
$form->setAttribute('style','width: 50%');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>

<div class="form-group">
<?php
echo $this->formRow($form->get('nome'));
?>
</div>
<div class="form-group">
<?php
echo $this->formRow($form->get('email'));
?>
</div>
<div class="form-group">
<?php
echo $this->formRow($form->get('password'));
?>
</div>
<div class="form-group">
<?php
echo $this->formSubmit($form->get('submit'));
?>
</div>

<?php
echo $this->form()->closeTag();
?>

